name: Samuel Toriel
title: Samuel Toriel's Blog
description: A blog about Software and Operations

markdown: kramdown
highlighter: rouge

extensions: [fenced_code_blocks]

paginate: 5

plugins:
  - jekyll-paginate

exclude:
  - docker-compose.yml
